// <auto-generated />
namespace MovieService.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddEditOthersMoviesPermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEditOthersMoviesPermission));
        
        string IMigrationMetadata.Id
        {
            get { return "201310171643035_Add EditOthersMoviesPermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
